expname: RS307_0_i2
data:
  datadir: [data/RS307, data/RS315, data/RS330, data/RS615]
  far: 4.5
  fov: 32.4
  imsize: 128  
  near: 1.5
  orthographic: Faqalse
  radius: 2.5
  type: RS307_0_i2
  umax: 1
  umin: 0
  vmax: 0.5
  vmin: 0
  v: 0.4, 0.3, 0.1
  white_bkgd: true
discriminator:
  num_classes: 4   
  hflip: false
  ndf: 64 #64 #128
nerf:
  N_importance: 0
  N_samples: 64
  decrease_noise: true
  i_embed: 0
  multires: 10
  multires_views: 4
  netdepth: 8
  netdepth_fine: 8
  netwidth: 256
  netwidth_fine: 256
  perturb: 1.0
  raw_noise_std: 1.0
  use_viewdirs: true
ray_sampler:
  N_samples: 1024 #4096
  max_scale: 1.0
  min_scale: 0.25
  scale_anneal: 0.0025
training:
  backup_every: 50000
  batch_size: 8
  chunk: 32768 #131072
  equalize_lr: false
  fid_every: 5000
  gan_type: standard
  lr_anneal: 0.5
  lr_anneal_every: 50000,100000,200000
  lr_d: 0.0001
  lr_g: 0.0007
  model_average_beta: 0.999
  model_average_reinit: false
  model_file: model.pt
  netchunk: 65536 #262144
  nworkers: 0
  optimizer: rmsprop
  outdir: ./results
  print_every: 10
  reg_param: 10.0
  reg_type: real
  restart_every: -1
  sample_every: 500
  save_best: fid
  save_every: 1000
  take_model_average: true
  use_amp: false
  video_every: 10000
z_dist:
  dim: 256
  dim_appearance: 0
  num_class: 4
  type: gauss
